version: "3"
services:
        mariadb:
                image: mariadb:10.3
                environment:
                        - MYSQL_DATABASE=devops
                        - MYSQL_USER=admin
                        - MYSQL_PASSWORD=admin
                        - MYSQL_ROOT_PASSWORD=admin
                volumes:
                        - ./mariadb/initial-data.sql:/docker-entrypoint-initdb.d/initial-data.sql
                networks:
                        - desafio

        nginx:
                image: nginx:1.13
                volumes:
                        - "./app:/var/www/html"
                        - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
                ports:
                        - "8000:80"
                depends_on:
                        - php

                networks:
                        - desafio

        php:
                build:
                        context: ./php
                volumes:
                        - "./app:/var/www/html"

                ports:
                        - "9000:9000"
                depends_on:
                        - mariadb
                environment:
                        - MYSQL_USER=admin
                        - MYSQL_PASSWORD=admin

                networks:
                        - desafio

        node:
                build:
                        context:
                                ./node
                volumes:
                        - "./node:/home/app"

                ports:
                        - "3000:3000"

                environment:
                        - NODE_ENV=development
                networks:
                        - desafio

        redis:
                image: redis
                ports:
                        - "6379:6379"

networks:
        desafio:
                driver: bridge
